from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from app.core.config import settings
from app.services import rule_engine


def sanction_number(app) -> str:
    return f"MoTA/{app.scheme_id}/{datetime.now().year}/{app.id:05d}"


def compute_amount(app) -> float:
    return rule_engine.sanction_amount(app.scheme_id, app.claimed_fee or 0)


def generate_pdf(app, sanction, officer_email: str) -> str:
    path = settings.GENERATED_DIR / "sanctions" / f"sanction_{app.id}.pdf"
    scheme = rule_engine.get_scheme(app.scheme_id)
    c = canvas.Canvas(str(path), pagesize=A4)
    w, h = A4

    c.setFillColor(colors.HexColor("#0b3d2e"))
    c.rect(0, h - 38 * mm, w, 38 * mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 15)
    c.drawString(20 * mm, h - 17 * mm, "Government of India - Ministry of Tribal Affairs")
    c.setFont("Helvetica", 10)
    c.drawString(20 * mm, h - 25 * mm, "MoTA-SANKALP | Scholarship Sanction Order (DEMO - not a legal document)")

    c.setFillColor(colors.black)
    y = h - 55 * mm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20 * mm, y, f"Sanction No: {sanction.sanction_number}")
    c.setFont("Helvetica", 10)
    c.drawRightString(w - 20 * mm, y, f"Date: {sanction.sanction_date.strftime('%d-%m-%Y')}")
    y -= 12 * mm

    rows = [
        ("Scheme", f"{scheme['name']} ({app.scheme_id})"),
        ("Application No", app.application_number),
        ("Beneficiary", app.full_name),
        ("Applicant ID", app.applicant_id or "-"),
        ("State", app.state or "-"),
        ("Course / Institution", f"{app.course or '-'} / {app.institution or '-'}"),
        ("Sanctioned Amount", f"Rs {sanction.amount:,.2f}"),
        ("Payment Mode", "DBT via PFMS"),
        ("AI Recommendation at decision", app.ai_recommendation or "-"),
        ("Sanctioning Officer", officer_email),
    ]
    for label, value in rows:
        c.setFont("Helvetica-Bold", 10)
        c.drawString(20 * mm, y, label)
        c.setFont("Helvetica", 10)
        c.drawString(75 * mm, y, str(value)[:80])
        y -= 8 * mm

    y -= 6 * mm
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(20 * mm, y, "Sanctioned after officer review. AI scrutiny outputs were advisory only.")
    y -= 5 * mm
    c.drawString(20 * mm, y, "Digitally generated by MoTA-SANKALP. e-Sign integration is mocked in this MVP.")
    c.setFont("Helvetica", 8)
    c.drawString(20 * mm, 15 * mm, f"Generated {datetime.now(timezone.utc).isoformat(timespec='seconds')} UTC")
    c.showPage()
    c.save()
    return str(path)
