"""feat: Phase 5 - Create Applicant model

Revision ID: 0649ba87818f
Revises: 9a733b39e364
Create Date: 2026-09-22 00:47:18.212164

"""
from alembic import op
import sqlalchemy as sa


revision = '0649ba87818f'
down_revision = '9a733b39e364'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###