"""feat: Phase 5 - Create Applicant model

Revision ID: 9a733b39e364
Revises: d3c93dce3902
Create Date: 2026-09-22 00:47:06.636374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9a733b39e364'
down_revision = 'd3c93dce3902'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('address', sa.String(length=500), nullable=True))
    op.alter_column('applicants', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('applicants', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('applicants', 'category',
               existing_type=postgresql.ENUM('ST', 'SC', 'OBC', 'GENERAL', name='categoryenum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('applicants', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='genderenum'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index('ix_applicants_external_id', table_name='applicants')
    op.create_unique_constraint(None, 'applicants', ['email'])
    op.drop_column('applicants', 'masked_aadhaar')
    op.drop_column('applicants', 'pvtg_status')
    op.drop_column('applicants', 'external_id')
    op.drop_column('applicants', 'state')
    op.drop_column('applicants', 'district')
    op.drop_column('applicants', 'dob')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('dob', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('applicants', sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('applicants', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('applicants', sa.Column('external_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('applicants', sa.Column('pvtg_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('applicants', sa.Column('masked_aadhaar', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'applicants', type_='unique')
    op.create_index('ix_applicants_external_id', 'applicants', ['external_id'], unique=False)
    op.alter_column('applicants', 'gender',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='genderenum'),
               existing_nullable=False)
    op.alter_column('applicants', 'category',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ST', 'SC', 'OBC', 'GENERAL', name='categoryenum'),
               existing_nullable=False)
    op.alter_column('applicants', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('applicants', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('applicants', 'address')
    # ### end Alembic commands ###