"""feat: Phase 5 - Update Application model with eligibility fields

Revision ID: d3c93dce3902
Revises: ffb3c8e702ec
Create Date: 2026-09-21 23:30:11.801686

"""
from alembic import op
import sqlalchemy as sa


revision = 'd3c93dce3902'
down_revision = 'ffb3c8e702ec'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('applications', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('applications', sa.Column('qualification', sa.String(length=255), nullable=False))
    op.add_column('applications', sa.Column('gender', sa.String(length=20), nullable=False))
    op.alter_column('applications', 'annual_income',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index('ix_applications_application_number', table_name='applications')
    op.drop_column('applications', 'institution')
    op.drop_column('applications', 'marks_percentage')
    op.drop_column('applications', 'submission_date')
    op.drop_column('applications', 'academic_year')
    op.drop_column('applications', 'current_stage')
    op.drop_column('applications', 'application_number')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('application_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('current_stage', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('academic_year', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('submission_date', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('marks_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('institution', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_applications_application_number', 'applications', ['application_number'], unique=False)
    op.alter_column('applications', 'annual_income',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('applications', 'gender')
    op.drop_column('applications', 'qualification')
    op.drop_column('applications', 'age')
    op.drop_column('applications', 'category')
    # ### end Alembic commands ###