"""Initial schema with 13 entities

Revision ID: fd3d0e76baf4
Revises: 
Create Date: 2026-09-21 22:49:13.182888

"""
from alembic import op
import sqlalchemy as sa


revision = 'fd3d0e76baf4'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=False),
    sa.Column('category', sa.Enum('ST', 'SC', 'OBC', 'GENERAL', name='categoryenum'), nullable=False),
    sa.Column('pvtg_status', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('masked_aadhaar', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicants_external_id'), 'applicants', ['external_id'], unique=True)
    op.create_index(op.f('ix_applicants_id'), 'applicants', ['id'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('MINISTRY_NODAL_OFFICER', 'STATE_NODAL_OFFICER', 'DISTRICT_NODAL_OFFICER', 'SCRUTINY_OFFICER', 'AUDITOR', 'ADMIN', name='roleenum'), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('application_number', sa.String(length=50), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.String(length=50), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'UNDER_SCRUTINY', 'DEFECTIVE', 'MANUAL_REVIEW', 'RECOMMEND_ELIGIBLE', 'RECOMMEND_INELIGIBLE', 'APPROVED', 'REJECTED', 'SANCTIONED', 'PAYMENT_PENDING', 'PAID', name='statusenum'), nullable=False),
    sa.Column('annual_income', sa.Float(), nullable=True),
    sa.Column('marks_percentage', sa.Float(), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('submission_date', sa.String(length=10), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_application_number'), 'applications', ['application_number'], unique=True)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('discrepancies',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('expected_value', sa.String(length=500), nullable=True),
    sa.Column('observed_value', sa.String(length=500), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severityenum'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'MANUAL_REVIEW', name='discrepancystatusenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discrepancies_id'), 'discrepancies', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('ST_CERTIFICATE', 'INCOME_CERTIFICATE', 'PG_MARKSHEET', 'ADMISSION_PROOF', 'BANK_PROOF', 'IDENTITY_PROOF', 'OTHER', name='documenttypeenum'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('phash', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'FLAGGED', name='verificationstatusenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('officer_actions',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officer_actions_id'), 'officer_actions', ['id'], unique=False)
    op.create_table('risk_results',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('duplicate_score', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevelenum'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_results_id'), 'risk_results', ['id'], unique=False)
    op.create_table('rule_results',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('actual_value', sa.String(length=500), nullable=True),
    sa.Column('expected_condition', sa.String(length=500), nullable=True),
    sa.Column('result', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_results_id'), 'rule_results', ['id'], unique=False)
    op.create_table('sanctions',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('sanction_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'APPROVED', 'REJECTED', 'PAID', name='sanctionstatusenum'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_sanctions_id'), 'sanctions', ['id'], unique=False)
    op.create_index(op.f('ix_sanctions_sanction_number'), 'sanctions', ['sanction_number'], unique=True)
    op.create_table('agent_resolutions',
    sa.Column('discrepancy_id', sa.Integer(), nullable=False),
    sa.Column('proposed_resolution', sa.Text(), nullable=False),
    sa.Column('supporting_document_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['discrepancy_id'], ['discrepancies.id'], ),
    sa.ForeignKeyConstraint(['supporting_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_resolutions_id'), 'agent_resolutions', ['id'], unique=False)
    op.create_table('document_extractions',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('structured_fields', sa.String(length=2000), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('layout_detection', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_extractions_id'), 'document_extractions', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('sanction_id', sa.Integer(), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='paymentstatusenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sanction_id'], ['sanctions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_reference')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_document_extractions_id'), table_name='document_extractions')
    op.drop_table('document_extractions')
    op.drop_index(op.f('ix_agent_resolutions_id'), table_name='agent_resolutions')
    op.drop_table('agent_resolutions')
    op.drop_index(op.f('ix_sanctions_sanction_number'), table_name='sanctions')
    op.drop_index(op.f('ix_sanctions_id'), table_name='sanctions')
    op.drop_table('sanctions')
    op.drop_index(op.f('ix_rule_results_id'), table_name='rule_results')
    op.drop_table('rule_results')
    op.drop_index(op.f('ix_risk_results_id'), table_name='risk_results')
    op.drop_table('risk_results')
    op.drop_index(op.f('ix_officer_actions_id'), table_name='officer_actions')
    op.drop_table('officer_actions')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_discrepancies_id'), table_name='discrepancies')
    op.drop_table('discrepancies')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_application_number'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_applicants_id'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_external_id'), table_name='applicants')
    op.drop_table('applicants')
    # ### end Alembic commands ###