"""feat: Phase 4 - SchemeConfig model

Revision ID: ffb3c8e702ec
Revises: fd3d0e76baf4
Create Date: 2026-09-21 23:19:06.181916

"""
from alembic import op
import sqlalchemy as sa


revision = 'ffb3c8e702ec'
down_revision = 'fd3d0e76baf4'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###